### ISSUE TITLE
CrashLoop

### ISSUE THREAD

**Issue by fwatermann** [SmartCity-2022/Service-Strassenverkehrsamt#10]
```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
self.run()
File "/code/rabbitmq/receiver.py", line 13, in run
Traceback (most recent call last):
File "/code/manage.py", line 22, in <module>
connection = pika.BlockingConnection(
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
main()
File "/code/manage.py", line 18, in main
self._impl = self._create_connection(parameters, _impl_class) execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
utility.execute()
File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
settings.INSTALLED_APPS
File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 87, in __getattr__
self._setup(name)
File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 74, in _setup
self._wrapped = Settings(settings_module)
File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 183, in __init__
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/code/SmartCity/settings.py", line 148, in <module>
send(key=configParser.get("rabbitMQ-routes", "HELLO"), headers=None, properties=None, payload="")
File "/code/rabbitmq/sender.py", line 13, in send
connection = pika.BlockingConnection(
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
self._impl = self._create_connection(parameters, _impl_class)
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
```

**Comment by fwatermann** [comment]
Mögliche Lösung:
Bei `exchange_declare` den Parameter `durable` auf `true` setzen.
