### ISSUE TITLE
Exception on backend startup

### ISSUE THREAD

**Issue by fwatermann** [SmartCity-2022/Service-Strassenverkehrsamt#14]
```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/code/rabbitmq/receiver.py", line 46, in run
channel.start_consuming()
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 1865, in start_consuming
self._process_data_events(time_limit=None)
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 2026, in _process_data_events
self.connection.process_data_events(time_limit=time_limit)
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 833, in process_data_events
self._dispatch_channel_events()
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
impl_channel._get_cookie()._dispatch_events()
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 1492, in _dispatch_events
consumer_info.on_message_callback(self, evt.method,
File "/code/rabbitmq/receiver.py", line 40, in callback
with open(configPath, "w") as configFile:
OSError: [Errno 30] Read-only file system: './config/config.cfg'
```

Die Config wird als ReadOnly gemappt. Daher schreibzugriffe nicht erlaubt.

**Comment by KevFischer** [comment]
Das ist dann ja aber vom System her richtig? Wenn ja was wäre hier ein geeigneter Lösungsansatz

**Comment by fwatermann** [comment]
Du solltest eigentlich zu keinem Zeitpunkt die Config bearbeiten, da die beim nächsten Neustart so oder so wieder zurückgesetzt wäre. Daher wenn du eine Variable speichern musst, bei dir gerade wahrscheinlich das JWT-Secret, verwende eine globale Variable.
