### ISSUE TITLE
Warnung im Frontend bezüglich List-Object

### ISSUE THREAD

**Issue by KevFischer** [SmartCity-2022/Service-Strassenverkehrsamt#20]
Finde keinen geeigneten Lösungansatz für den Fehler, der stört an sich nicht, aber die Exception ist halt nicht schön

`react-jsx-dev-runtime.development.js:97 Warning: Each child in a list should have a unique "key" prop.
Check the render method of "TableList". See https://reactjs.org/link/warning-keys for more information.
    at td
    at TableList (http://localhost:3000/static/js/bundle.js:391:13)
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:50622:30)
    at http://localhost:3000/static/js/bundle.js:18340:5
    at http://localhost:3000/static/js/bundle.js:16809:5
    at http://localhost:3000/static/js/bundle.js:17976:5
    at div
    at http://localhost:3000/static/js/bundle.js:18432:7
    at Tabs (http://localhost:3000/static/js/bundle.js:4439:9)
    at Tabs (http://localhost:3000/static/js/bundle.js:18181:70)
    at div
    at Fahrzeuge (http://localhost:3000/static/js/bundle.js:1736:80)
    at Routes (http://localhost:3000/static/js/bundle.js:50424:5)
    at Router (http://localhost:3000/static/js/bundle.js:50357:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:49166:5)`

**Comment by fwatermann** [comment]
Du musst ein Feld haben wie `id`, jeder Datensatz muss ein uniquen wert haben, damit eine Zeile genau diesem Datensatz zugeordnet werden kann.
