### ISSUE TITLE
Exception in frontend

### ISSUE THREAD

**Issue by KevFischer** [SmartCity-2022/Service-Strassenverkehrsamt#29]
`Failed to load resource: the server responded with a status of 502 (Bad Gateway)` 

Bräuchte einmal infos ob der Server was ausgibt, die verification ist immernoch Fehlerhaft

**Comment by fwatermann** [comment]
```txt
 [x] Sent 'service.hello':''
 [*] Waiting for Events. To exit press CTRL+C
 [x] Sent 'service.hello':''
 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message:  

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 

 [*] Waiting for Events. To exit press CTRL+C
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 558, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (corsheaders.E014) Origin 'http://smartcity.w-mi.de/' in CORS_ALLOWED_ORIGINS should not have path

System check identified 1 issue (0 silenced).
 ---Event received--- 
 [x] Routing Key: service.mainhub.logout
 [x] Message: {"msg":"logout"} 

 ---Event received--- 
 [x] Routing Key: service.mainhub.logout
 [x] Message: {"msg":"logout"} 

 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message:  

 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message:  

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 

 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message: buergerbuero 

 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message: buergerbuero 

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 

 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message: buergerbuero 

 ---Event received--- 
 [x] Routing Key: service.hello
 [x] Message: buergerbuero 

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 

 ---Event received--- 
 [x] Routing Key: service.world
 [x] Message: 4c029052c43b087bb01b574df541101c56091fe2c9b7bc63d1a58706a698e7a5c25461c606ff469f412d524c3a9efd0e3476e708183e933dac37aa66e04e3668 
```
